# Generated by Django 5.0.4 on 2024-08-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sliderimg_btn_href_sliderimg_btn_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimg',
            name='header',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sliderimg',
            name='text',
            field=models.CharField(max_length=30),
        ),
    ]
