# Generated by Django 5.0.4 on 2024-08-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sliderimg_header_alter_sliderimg_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimg',
            name='btn_text_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sliderimg',
            name='btn_text_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sliderimg',
            name='btn_text_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sliderimg',
            name='header_az',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sliderimg',
            name='header_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sliderimg',
            name='header_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sliderimg',
            name='text_az',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sliderimg',
            name='text_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sliderimg',
            name='text_ru',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
