# Generated by Django 5.0.4 on 2024-07-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='cover',
            field=models.ImageField(default=1, upload_to='FrameCoverIMGs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
