# Generated by Django 5.0.4 on 2024-07-08 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_frame_cover_product_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='detail',
        ),
    ]
