# Generated by Django 5.0.4 on 2024-07-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_description_product_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='frames',
            field=models.ManyToManyField(blank=True, to='product.frame'),
        ),
    ]
