# Generated by Django 5.0.4 on 2024-07-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_frames'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='price',
            field=models.FloatField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='size',
            name='price_glass',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='size',
            name='price_mdf',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
