# Generated by Django 5.0.4 on 2024-08-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_frame_price_size_price_glass_size_price_mdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdiscount',
            name='type',
        ),
    ]
