# Generated by Django 5.0.4 on 2024-07-06 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_basketitem_image_order_orderitem_order_products'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='image',
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.frame'),
        ),
    ]
