# Generated by Django 5.0.4 on 2024-08-07 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_basketitem_image_alter_basketitem_frame'),
        ('product', '0006_frame_price_size_price_glass_size_price_mdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='coupon',
            new_name='used_coupon',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pay_method',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_actual_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delv_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.frame'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='OrderIMGs/'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.size'),
        ),
    ]
