# Generated by Django 5.0.4 on 2024-08-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_coupon_order_used_coupon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payed_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='order_actual_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
