# Generated by Django 5.0.4 on 2024-08-07 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_payed_amount_order_order_actual_price_and_more'),
        ('product', '0006_frame_price_size_price_glass_size_price_mdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.frame'),
        ),
    ]
